version: "3.8"
networks:
  alsinet:
    external: true
services:
  web:
    build: .
    container_name: mlops2
    image: mlops2
    ports:
      - 1234:5050
    environment:
      - FLASK_RUN_PORT=$FLASK_RUN_PORT
      - FLASK_HOST=$FLASKHOST
      - FLASK_APP=$FLASK_APP
      - DB_URL=$DB_URL
      - CONFIG=$CONFIG
      - SECRET_KEY=$SECRET_KEY
    volumes:
      - .env:/usr/src/app/mlops2/.env
    networks:
      - alsinet

  sql:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./sql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - alsinet
